<a href="https://colab.research.google.com/github/doremon020848/stat-2/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [2]:

a = torch.tensor([1.])
a


tensor([1.])

### Convert a tensor to scalar

In [3]:
b = a[0].item()
b

1.0

### Creating 2D tensor

In [4]:
c = torch.tensor([[1., 2.], [3., 4.]])
c

tensor([[1., 2.],
        [3., 4.]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [5]:
d = c.numpy()
d

array([[1., 2.],
       [3., 4.]], dtype=float32)

### Convert from numpy array to tensor

In [6]:
f = torch.from_numpy(d)
f

tensor([[1., 2.],
        [3., 4.]])

## PyTorch and GPU

check if GPU is available

In [7]:
torch.cuda.is_available()

True

In [8]:

c = c.cuda()
c

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [9]:

e = c.cpu().numpy()
e

array([[1., 2.],
       [3., 4.]], dtype=float32)

## Basic operations

In [10]:
c * 2

tensor([[2., 4.],
        [6., 8.]], device='cuda:0')

In [11]:
c - 1

tensor([[0., 1.],
        [2., 3.]], device='cuda:0')

### Matrix multiplication

In [12]:

A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [13]:

torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [14]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [15]:

A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [16]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [17]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [18]:

I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
R1 = torch.rand(2, 3)
R1

tensor([[0.1785, 0.6268, 0.5634],
        [0.4432, 0.0543, 0.0634]])

In [20]:
R2 = torch.randn(2, 3)
R2

tensor([[ 0.1726, -1.0097,  2.2041],
        [ 2.1237,  0.4195, -2.1373]])

In [21]:

a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [22]:

R1.shape

torch.Size([2, 3])

### Checking the shape of a tensor

In [23]:
u = torch.arange(6)
u.shape

torch.Size([6])

### Changing the shape of a tensor

In [24]:

v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [25]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [26]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [27]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [28]:
# concatenate
e = torch.cat([a, b], axis=0)
e # มิติเท่าเดิม

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [29]:
display(a,b)

tensor([0, 1, 2, 3])

tensor([1, 2, 3, 4])

In [30]:
f = torch.cat([a.reshape(2, 2), b.reshape(2, 2)], axis=0)
f

tensor([[0, 1],
        [2, 3],
        [1, 2],
        [3, 4]])

### Squeezing a tensor (removing an extra dimension)

In [31]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [32]:

C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )


## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

In [35]:

torch.inverse(torch.tensor([[1., 2.], [3., 4.]]))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [36]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [37]:

X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

In [38]:

one = torch.ones(200, 1)

In [39]:

X

tensor([[-0.1599,  0.4466,  0.2982,  ...,  0.7831, -1.3569,  0.0382],
        [-0.8346,  0.6311,  0.9726,  ..., -1.1157,  2.0119,  0.2596],
        [-0.6180, -0.1153, -1.2071,  ..., -0.5525,  0.3203, -0.0247],
        ...,
        [-2.3715, -1.0888,  0.3168,  ...,  0.2135, -1.6337, -0.1203],
        [ 1.3897,  0.3339, -0.0710,  ...,  0.6472, -1.5126,  0.5338],
        [-0.0294, -0.2747, -0.7134,  ..., -0.6935, -0.2898, -1.6135]])

In [40]:

X = torch.cat([one, X], axis=1)
X

tensor([[ 1.0000, -0.1599,  0.4466,  ...,  0.7831, -1.3569,  0.0382],
        [ 1.0000, -0.8346,  0.6311,  ..., -1.1157,  2.0119,  0.2596],
        [ 1.0000, -0.6180, -0.1153,  ..., -0.5525,  0.3203, -0.0247],
        ...,
        [ 1.0000, -2.3715, -1.0888,  ...,  0.2135, -1.6337, -0.1203],
        [ 1.0000,  1.3897,  0.3339,  ...,  0.6472, -1.5126,  0.5338],
        [ 1.0000, -0.0294, -0.2747,  ..., -0.6935, -0.2898, -1.6135]])

In [41]:
y = X @ b + e
y

tensor([[-0.6165],
        [-0.1949],
        [-0.4885],
        [ 0.6676],
        [ 1.8468],
        [-0.3446],
        [ 1.1997],
        [-3.1453],
        [ 2.0921],
        [-0.7204],
        [ 0.3173],
        [ 0.6230],
        [ 1.1931],
        [ 0.6609],
        [-0.1131],
        [ 2.1030],
        [ 3.4077],
        [ 4.5869],
        [-0.7776],
        [-0.0601],
        [ 0.2128],
        [ 0.2050],
        [ 3.2107],
        [-0.5720],
        [-1.7141],
        [-4.2035],
        [ 0.4948],
        [-0.3406],
        [ 0.8164],
        [ 0.9137],
        [ 4.4871],
        [ 2.4264],
        [-1.9436],
        [-2.3966],
        [ 0.7325],
        [-2.0004],
        [ 2.7221],
        [ 3.1937],
        [ 0.4112],
        [-2.5983],
        [ 1.8871],
        [-5.9548],
        [-3.9744],
        [-1.9241],
        [-1.9707],
        [ 1.1793],
        [-0.1228],
        [ 0.8739],
        [-0.0327],
        [-4.3697],
        [-0.1650],
        [-2.3556],
        [ 0.

In [42]:
b_hat = torch.inverse(X.t() @ X) @ X.t() @ y
b_hat

tensor([[ 0.3176],
        [ 1.6093],
        [ 1.0600],
        [-0.0177],
        [-0.5466],
        [ 0.4808],
        [ 0.2601],
        [-0.0101]])

In [43]:
y_hat = X @ b_hat
y_hat

tensor([[-7.8412e-03],
        [-7.8541e-01],
        [-6.2389e-01],
        [ 1.0582e+00],
        [ 2.4240e+00],
        [-4.9598e-01],
        [ 2.3116e+00],
        [-3.3381e+00],
        [ 2.6402e+00],
        [-1.7634e+00],
        [ 5.4033e-02],
        [ 7.6630e-01],
        [ 1.1914e+00],
        [ 6.9918e-01],
        [ 9.0398e-01],
        [ 2.3730e+00],
        [ 2.3167e+00],
        [ 4.1980e+00],
        [-1.8375e+00],
        [-1.6242e+00],
        [ 7.4375e-01],
        [ 1.7553e-01],
        [ 3.2766e+00],
        [ 4.9163e-01],
        [-3.2275e+00],
        [-5.1242e+00],
        [ 5.1811e-01],
        [-1.0612e+00],
        [ 2.1896e+00],
        [ 9.6713e-02],
        [ 2.9030e+00],
        [ 2.0906e+00],
        [-1.7938e+00],
        [-1.0688e+00],
        [-4.0345e-01],
        [-1.4775e+00],
        [ 3.3224e+00],
        [ 2.4858e+00],
        [ 7.7847e-01],
        [-1.8683e+00],
        [ 2.0000e+00],
        [-7.1001e+00],
        [-2.9081e+00],
        [-1

In [44]:

y = y.numpy()
y_hat = y_hat.numpy()

In [45]:
MSE = (1/200) * (np.sum((y - y_hat)**2))
MSE

np.float32(0.8583562)